window.LMS = {
  name: "LMS Academy",
  tagline: "Learn. Master. Build.",

  categories: [
    { id: "basics", name: "Computer Basics", icon: "pc" },
    { id: "web", name: "Web Development", icon: "code" },
    { id: "programming", name: "Programming", icon: "terminal" },
    { id: "datascience", name: "Data Science", icon: "chart" },
    { id: "ai", name: "AI & Machine Learning", icon: "brain" },
    { id: "cloud", name: "Cloud & DevOps", icon: "cloud" },
    { id: "security", name: "Cybersecurity", icon: "shield" },
    { id: "mobile", name: "Mobile Development", icon: "phone" },
    { id: "cs", name: "Computer Science", icon: "cpu" },
    { id: "db", name: "Databases", icon: "db" },
    { id: "math", name: "Math for IT", icon: "sigma" },
    { id: "design", name: "UI/UX for IT", icon: "pen" },
    { id: "career", name: "Career Skills", icon: "briefcase" }
  ],

  levels: ["Beginner", "Intermediate", "Advanced", "Expert"],

  courses: [
    {
      id: "computer-basics",
      title: "Computer Basics & Windows",
      instructor: "Farah Siddiqui",
      category: "basics",
      level: "Beginner",
      rating: 4.8,
      reviews: 9200,
      hours: 8,
      lectures: 42,
      students: 64000,
      price: "Free",
      badge: "Start here",
      desc: "First-day computer skills: power on, files, folders, USB, settings, and Windows without fear. True startup — before any coding.",
      outcomes: ["Use a PC with confidence", "Files, folders, copy & paste", "Windows settings & apps", "Print, save, and stay organized"]
    },
    {
      id: "ms-office",
      title: "MS Office: Word, Excel & PowerPoint",
      instructor: "Farah Siddiqui",
      category: "basics",
      level: "Beginner",
      rating: 4.9,
      reviews: 21400,
      hours: 16,
      lectures: 78,
      students: 128000,
      price: "Free",
      badge: "Most loved",
      desc: "Documents, spreadsheets, and slides from zero. The office toolkit every student and first job asks for.",
      outcomes: ["Word letters & CVs", "Excel tables & simple formulas", "PowerPoint presentations", "Print-ready office files"]
    },
    {
      id: "internet-google",
      title: "Internet, Email & Google Tools",
      instructor: "Omar Farooq",
      category: "basics",
      level: "Beginner",
      rating: 4.7,
      reviews: 6100,
      hours: 7,
      lectures: 36,
      students: 41000,
      price: "Free",
      badge: "",
      desc: "Browse safely, send email, attach files, and use Drive, Docs, and Meet. Everyday digital life, taught slowly.",
      outcomes: ["Safe browsing habits", "Gmail like a pro", "Google Drive & Docs", "Meet and calendar basics"]
    },
    {
      id: "typing-safety",
      title: "Typing, Files & Online Safety",
      instructor: "Hana Kim",
      category: "basics",
      level: "Beginner",
      rating: 4.6,
      reviews: 3800,
      hours: 6,
      lectures: 28,
      students: 27000,
      price: "Free",
      badge: "Startup",
      desc: "Keyboard skills, passwords, scams to ignore, and a clean desktop. The last beginner step before real IT courses.",
      outcomes: ["Faster, accurate typing", "Strong passwords", "Spot common scams", "A tidy digital workspace"]
    },
    {
      id: "html-css-foundations",
      title: "HTML, CSS & Web Foundations",
      instructor: "Ayesha Malik",
      category: "web",
      level: "Intermediate",
      rating: 4.8,
      reviews: 18420,
      hours: 18,
      lectures: 92,
      students: 210400,
      price: "Free",
      badge: "Start here",
      desc: "Build real pages from scratch. Structure, style, Flexbox, Grid, and accessible layouts — the first step of every web career.",
      outcomes: ["Semantic HTML pages", "Responsive layouts with Flexbox & Grid", "Accessible, clean CSS", "A personal portfolio site"]
    },
    {
      id: "javascript-zero",
      title: "JavaScript from Zero to Interactive",
      instructor: "Daniel Okonkwo",
      category: "programming",
      level: "Intermediate",
      rating: 4.7,
      reviews: 22110,
      hours: 32,
      lectures: 148,
      students: 189000,
      price: "Free",
      badge: "Bestseller",
      desc: "Variables to DOM, events, fetch, and small apps. Learn by building — the freeCodeCamp way, with marketplace-style structure.",
      outcomes: ["Core JS syntax & logic", "DOM and events", "APIs with fetch", "3 mini projects"]
    },
    {
      id: "python-beginners",
      title: "Python for Absolute Beginners",
      instructor: "Priya Raman",
      category: "programming",
      level: "Intermediate",
      rating: 4.9,
      reviews: 41200,
      hours: 24,
      lectures: 110,
      students: 340800,
      price: "Free",
      badge: "Most loved",
      desc: "The friendliest path into code. Syntax, data types, files, and problem solving used across data, AI, and backend work.",
      outcomes: ["Python syntax fluency", "Functions & modules", "File & error handling", "Beginner algorithms"]
    },
    {
      id: "git-github",
      title: "Git & GitHub Essentials",
      instructor: "Omar Farooq",
      category: "cs",
      level: "Intermediate",
      rating: 4.6,
      reviews: 9800,
      hours: 8,
      lectures: 36,
      students: 98000,
      price: "Free",
      badge: "",
      desc: "Version control the way teams actually work. Commits, branches, PRs, and a clean GitHub profile.",
      outcomes: ["Daily Git workflow", "Branching & merging", "Pull requests", "Portfolio-ready GitHub"]
    },
    {
      id: "sql-fundamentals",
      title: "SQL & Relational Databases",
      instructor: "Elena Petrova",
      category: "db",
      level: "Intermediate",
      rating: 4.8,
      reviews: 15600,
      hours: 16,
      lectures: 74,
      students: 142000,
      price: "Free",
      badge: "Career path",
      desc: "Query data like an analyst. SELECT to joins, aggregations, indexes, and designing simple schemas.",
      outcomes: ["Write real SQL queries", "Joins & aggregations", "Schema basics", "Practice on sample datasets"]
    },
    {
      id: "responsive-design",
      title: "Responsive Web Design Lab",
      instructor: "Ayesha Malik",
      category: "web",
      level: "Intermediate",
      rating: 4.7,
      reviews: 12340,
      hours: 14,
      lectures: 58,
      students: 88000,
      price: "Free",
      badge: "Project",
      desc: "Mobile-first pages, media queries, and a certification-style project set inspired by hands-on curricula.",
      outcomes: ["Mobile-first CSS", "Breakpoints that work", "Landing page project", "Form & survey pages"]
    },
    {
      id: "react-complete",
      title: "React.js — Components to Apps",
      instructor: "Noah Berg",
      category: "web",
      level: "Advanced",
      rating: 4.8,
      reviews: 30120,
      hours: 36,
      lectures: 162,
      students: 198000,
      price: "Included",
      badge: "Bestseller",
      desc: "Hooks, routing, state, and a full dashboard. Build the UI layer companies actually hire for.",
      outcomes: ["Hooks & composition", "Client-side routing", "API-driven UI", "Deployed React app"]
    },
    {
      id: "node-express",
      title: "Node.js & Express API Engineering",
      instructor: "Sofia Alvarez",
      category: "web",
      level: "Advanced",
      rating: 4.7,
      reviews: 17800,
      hours: 28,
      lectures: 120,
      students: 112000,
      price: "Included",
      badge: "",
      desc: "REST APIs, auth, middleware, and Mongo/SQL. The backend half of a full-stack career.",
      outcomes: ["REST API design", "JWT auth", "Middleware patterns", "CRUD with a database"]
    },
    {
      id: "data-python",
      title: "Data Analysis with Python",
      instructor: "Priya Raman",
      category: "datascience",
      level: "Advanced",
      rating: 4.8,
      reviews: 26400,
      hours: 30,
      lectures: 134,
      students: 176000,
      price: "Included",
      badge: "Career path",
      desc: "Pandas, NumPy, visualization, and storytelling with data — analyst-ready, not just notebook demos.",
      outcomes: ["Clean messy datasets", "Exploratory analysis", "Charts that explain", "A case-study report"]
    },
    {
      id: "java-dsa",
      title: "Java, OOP & Data Structures",
      instructor: "Rahul Mehta",
      category: "programming",
      level: "Advanced",
      rating: 4.6,
      reviews: 14300,
      hours: 40,
      lectures: 170,
      students: 91000,
      price: "Included",
      badge: "",
      desc: "Object-oriented Java plus lists, trees, and hashing — the CS core interviewers expect.",
      outcomes: ["OOP in Java", "Core data structures", "Complexity basics", "Coding-problem practice"]
    },
    {
      id: "linux-cli",
      title: "Linux, Shell & Developer Toolkit",
      instructor: "Omar Farooq",
      category: "cloud",
      level: "Advanced",
      rating: 4.7,
      reviews: 8700,
      hours: 12,
      lectures: 48,
      students: 67000,
      price: "Free",
      badge: "",
      desc: "The command line, permissions, processes, and scripts every cloud and DevOps path needs.",
      outcomes: ["Comfortable in the shell", "Permissions & processes", "Bash scripts", "SSH & servers"]
    },
    {
      id: "uiux-devs",
      title: "UI/UX Fundamentals for Developers",
      instructor: "Hana Kim",
      category: "design",
      level: "Advanced",
      rating: 4.8,
      reviews: 6400,
      hours: 15,
      lectures: 62,
      students: 54000,
      price: "Included",
      badge: "",
      desc: "Spacing, type, color, and flows so your apps feel designed — not just functional.",
      outcomes: ["Visual hierarchy", "Component consistency", "Simple user flows", "A redesigned UI case"]
    },
    {
      id: "ml-az",
      title: "Machine Learning — Theory to Practice",
      instructor: "Dr. Leila Hassan",
      category: "ai",
      level: "Advanced",
      rating: 4.9,
      reviews: 19800,
      hours: 48,
      lectures: 190,
      students: 128000,
      price: "Included",
      badge: "Top rated",
      desc: "Regression to neural nets, evaluation, and real datasets. Professional-track depth with guided labs.",
      outcomes: ["Supervised learning", "Model evaluation", "Feature work", "End-to-end ML project"]
    },
    {
      id: "aws-architect",
      title: "AWS Cloud: Practitioner to Architect",
      instructor: "James Whitaker",
      category: "cloud",
      level: "Advanced",
      rating: 4.7,
      reviews: 11200,
      hours: 42,
      lectures: 156,
      students: 76000,
      price: "Included",
      badge: "Career path",
      desc: "Core AWS services, architecture patterns, and exam-aligned practice for cloud roles.",
      outcomes: ["Core AWS services", "VPC & IAM", "High-availability design", "Exam-style drills"]
    },
    {
      id: "cyber-plus",
      title: "Cybersecurity Foundations Plus",
      instructor: "Nadia Rahman",
      category: "security",
      level: "Advanced",
      rating: 4.8,
      reviews: 9100,
      hours: 26,
      lectures: 98,
      students: 61000,
      price: "Included",
      badge: "",
      desc: "Threats, network security, crypto basics, and defensive thinking — a serious start, not scare headlines.",
      outcomes: ["Threat landscape", "Network security", "Crypto basics", "Incident response intro"]
    },
    {
      id: "docker-k8s",
      title: "Docker, Kubernetes & DevOps Pipelines",
      instructor: "Sofia Alvarez",
      category: "cloud",
      level: "Advanced",
      rating: 4.8,
      reviews: 13400,
      hours: 34,
      lectures: 128,
      students: 82000,
      price: "Included",
      badge: "Bestseller",
      desc: "Containers, orchestration, CI/CD, and the production habits that separate demos from delivery.",
      outcomes: ["Docker images & compose", "K8s core objects", "CI/CD pipelines", "Observability basics"]
    },
    {
      id: "flutter-apps",
      title: "Flutter: Cross-Platform Mobile Apps",
      instructor: "Kenji Sato",
      category: "mobile",
      level: "Advanced",
      rating: 4.6,
      reviews: 7200,
      hours: 28,
      lectures: 118,
      students: 49000,
      price: "Included",
      badge: "",
      desc: "Widgets, state, APIs, and a shippable app for Android and iOS from one codebase.",
      outcomes: ["Flutter UI", "State management", "API integration", "Published-style app"]
    },
    {
      id: "nextjs-fullstack",
      title: "Next.js Full-Stack Applications",
      instructor: "Noah Berg",
      category: "web",
      level: "Advanced",
      rating: 4.8,
      reviews: 8900,
      hours: 32,
      lectures: 124,
      students: 58000,
      price: "Included",
      badge: "",
      desc: "App Router, server components, auth, and databases — modern full-stack in one framework.",
      outcomes: ["App Router fluency", "Server vs client", "Auth & data", "Production deploy"]
    },
    {
      id: "pytorch-dl",
      title: "Deep Learning with PyTorch",
      instructor: "Dr. Leila Hassan",
      category: "ai",
      level: "Expert",
      rating: 4.9,
      reviews: 5400,
      hours: 50,
      lectures: 168,
      students: 31000,
      price: "Included",
      badge: "Expert",
      desc: "Tensors, CNNs, transformers intro, and training loops. For learners ready to go past introductory ML.",
      outcomes: ["PyTorch workflow", "CNNs & transfer learning", "Training discipline", "Research-style notebook"]
    },
    {
      id: "system-design",
      title: "System Design for Interviews & Jobs",
      instructor: "Rahul Mehta",
      category: "cs",
      level: "Expert",
      rating: 4.8,
      reviews: 10100,
      hours: 22,
      lectures: 72,
      students: 64000,
      price: "Included",
      badge: "Interview",
      desc: "Load, storage, caches, queues, and trade-offs. Design systems you can actually explain on a whiteboard.",
      outcomes: ["Back-of-envelope estimates", "Core building blocks", "Case-study designs", "Interview frameworks"]
    },
    {
      id: "ethical-hacking",
      title: "Ethical Hacking & Defensive Labs",
      instructor: "Nadia Rahman",
      category: "security",
      level: "Advanced",
      rating: 4.7,
      reviews: 6800,
      hours: 38,
      lectures: 140,
      students: 42000,
      price: "Included",
      badge: "Lab-heavy",
      desc: "Recon, web vulns, and hardening — always in a legal lab. Offense to understand defense.",
      outcomes: ["Lab methodology", "Common web vulns", "Hardening habits", "Write-up practice"]
    },
    {
      id: "discrete-math",
      title: "Discrete Math for Programmers",
      instructor: "Prof. Martin Cole",
      category: "math",
      level: "Advanced",
      rating: 4.8,
      reviews: 4300,
      hours: 20,
      lectures: 80,
      students: 39000,
      price: "Free",
      badge: "Study hub",
      desc: "Logic, sets, proofs, and graphs — Khan-style mastery with IT examples, not dry textbooks.",
      outcomes: ["Propositional logic", "Sets & functions", "Graphs", "Proof intuition"]
    },
    {
      id: "lin-alg-ml",
      title: "Linear Algebra for Machine Learning",
      instructor: "Prof. Martin Cole",
      category: "math",
      level: "Advanced",
      rating: 4.9,
      reviews: 5100,
      hours: 18,
      lectures: 66,
      students: 28000,
      price: "Free",
      badge: "Study hub",
      desc: "Vectors, matrices, and eigenvalues with visual intuition — the math that makes ML click.",
      outcomes: ["Vector spaces intuition", "Matrix operations", "Eigen ideas", "ML connections"]
    },
    {
      id: "dsa-mastery",
      title: "Data Structures & Algorithms Mastery",
      instructor: "Daniel Okonkwo",
      category: "cs",
      level: "Advanced",
      rating: 4.9,
      reviews: 22000,
      hours: 55,
      lectures: 210,
      students: 150000,
      price: "Included",
      badge: "Interview",
      desc: "Patterns, complexity, and hundreds of guided problems. From arrays to graphs — hire-ready DSA.",
      outcomes: ["Pattern recognition", "Time/space analysis", "Trees, graphs, DP", "Interview problem set"]
    },
    {
      id: "stats-it",
      title: "Statistics & Probability for IT",
      instructor: "Elena Petrova",
      category: "math",
      level: "Advanced",
      rating: 4.7,
      reviews: 3900,
      hours: 16,
      lectures: 70,
      students: 33000,
      price: "Free",
      badge: "Study hub",
      desc: "Distributions, sampling, and inference with data-job examples. Mastery checks after every unit.",
      outcomes: ["Descriptive stats", "Probability models", "Sampling", "Simple inference"]
    },
    {
      id: "career-tech",
      title: "Tech Career: Portfolio, Interviews & Offers",
      instructor: "Prof. Martin Cole",
      category: "career",
      level: "Advanced",
      rating: 4.8,
      reviews: 2700,
      hours: 10,
      lectures: 40,
      students: 21000,
      price: "Free",
      badge: "Career",
      desc: "Resume, GitHub story, STAR interviews, and how to talk about projects without fluff.",
      outcomes: ["Portfolio narrative", "Resume that scans", "Interview stories", "Offer basics"]
    },
    {
      id: "excel-dashboards",
      title: "Excel Dashboards for School & Office",
      instructor: "Farah Siddiqui",
      category: "basics",
      level: "Beginner",
      rating: 4.8,
      reviews: 5400,
      hours: 9,
      lectures: 44,
      students: 38000,
      price: "Free",
      badge: "New",
      desc: "Charts, tables, and a clean one-page dashboard. No coding — just Excel people actually open at work.",
      outcomes: ["Clean data tables", "Charts that read clearly", "A one-page dashboard", "Print and share a report"]
    },
    {
      id: "chrome-pc-habits",
      title: "Chrome, Shortcuts & Daily PC Habits",
      instructor: "Omar Farooq",
      category: "basics",
      level: "Beginner",
      rating: 4.7,
      reviews: 2100,
      hours: 5,
      lectures: 24,
      students: 19000,
      price: "Free",
      badge: "",
      desc: "Tabs, downloads, bookmarks, keyboard shortcuts, and a desktop that stays tidy.",
      outcomes: ["Browser without chaos", "Useful shortcuts", "Downloads you can find", "A calmer desktop"]
    },
    {
      id: "meetings-zoom",
      title: "Zoom, Meet & Online Class Etiquette",
      instructor: "Farah Siddiqui",
      category: "basics",
      level: "Beginner",
      rating: 4.6,
      reviews: 1800,
      hours: 4,
      lectures: 20,
      students: 16000,
      price: "Free",
      badge: "Startup",
      desc: "Join a call, share a screen, mute at the right time, and look ready for class or a first job interview.",
      outcomes: ["Join and host a call", "Share screen cleanly", "Camera and audio basics", "Simple meeting manners"]
    },
    {
      id: "vscode-first",
      title: "VS Code: Your First Coding Setup",
      instructor: "Daniel Okonkwo",
      category: "programming",
      level: "Intermediate",
      rating: 4.8,
      reviews: 7200,
      hours: 6,
      lectures: 32,
      students: 54000,
      price: "Free",
      badge: "New",
      desc: "Install the editor, open a folder, run a file, and debug without fear. The workshop before every language course.",
      outcomes: ["A working VS Code setup", "Extensions that help", "Run and debug a file", "Git inside the editor"]
    },
    {
      id: "bootstrap-layouts",
      title: "Bootstrap Layouts for Real Pages",
      instructor: "Ayesha Malik",
      category: "web",
      level: "Intermediate",
      rating: 4.7,
      reviews: 6100,
      hours: 10,
      lectures: 48,
      students: 41000,
      price: "Free",
      badge: "",
      desc: "Grid, navbar, cards, and forms. Ship a landing page that looks finished on phone and desktop.",
      outcomes: ["Bootstrap grid fluency", "Navbar and hero", "Forms that validate", "A live landing page"]
    },
    {
      id: "python-scripts",
      title: "Python Scripts for Everyday Tasks",
      instructor: "Priya Raman",
      category: "programming",
      level: "Intermediate",
      rating: 4.8,
      reviews: 8900,
      hours: 12,
      lectures: 56,
      students: 67000,
      price: "Free",
      badge: "Bestseller",
      desc: "Rename files, clean a CSV, hit a simple API. Python as a tool, not a textbook.",
      outcomes: ["Scripts you will reuse", "Files and folders in Python", "CSV cleanup", "A tiny automation project"]
    },
    {
      id: "typescript-js",
      title: "TypeScript for JavaScript Developers",
      instructor: "Noah Berg",
      category: "programming",
      level: "Advanced",
      rating: 4.8,
      reviews: 11200,
      hours: 14,
      lectures: 68,
      students: 72000,
      price: "Included",
      badge: "New",
      desc: "Types, interfaces, and safer React/Node code. The language teams expect after JavaScript.",
      outcomes: ["Core TypeScript types", "Interfaces and generics", "Typed API calls", "A migrated mini app"]
    },
    {
      id: "mongodb-node",
      title: "MongoDB with Node APIs",
      instructor: "Sofia Alvarez",
      category: "db",
      level: "Advanced",
      rating: 4.7,
      reviews: 5400,
      hours: 11,
      lectures: 52,
      students: 39000,
      price: "Included",
      badge: "",
      desc: "Collections, queries, indexes, and a CRUD API. Data that survives a refresh.",
      outcomes: ["Document modeling", "CRUD with Mongoose", "Indexes that help", "An API with real data"]
    },
    {
      id: "pandas-stories",
      title: "Pandas, Charts & Data Stories",
      instructor: "Priya Raman",
      category: "datascience",
      level: "Advanced",
      rating: 4.8,
      reviews: 7600,
      hours: 13,
      lectures: 60,
      students: 51000,
      price: "Included",
      badge: "Career path",
      desc: "Clean a messy table, plot what matters, and write a one-page finding. Analyst work, not notebook tourism.",
      outcomes: ["Clean with Pandas", "Charts that explain", "A written finding", "A shareable notebook"]
    },
    {
      id: "llm-apps",
      title: "LLM Apps: Prompts, RAG & Guardrails",
      instructor: "Dr. Leila Hassan",
      category: "ai",
      level: "Expert",
      rating: 4.7,
      reviews: 3200,
      hours: 16,
      lectures: 64,
      students: 24000,
      price: "Included",
      badge: "New",
      desc: "Prompt patterns, retrieval, and a small app that answers from your own notes — with limits, not hype.",
      outcomes: ["Reliable prompt patterns", "Simple RAG pipeline", "Safety checks", "A documented demo app"]
    },
    {
      id: "terraform-aws",
      title: "Terraform on AWS: Infra as Code",
      instructor: "James Whitaker",
      category: "cloud",
      level: "Expert",
      rating: 4.8,
      reviews: 4100,
      hours: 18,
      lectures: 72,
      students: 28000,
      price: "Included",
      badge: "",
      desc: "Providers, state, modules, and a repeatable VPC. Cloud you can rebuild, not click together once.",
      outcomes: ["Terraform workflow", "Reusable modules", "Remote state", "A rebuildable AWS lab"]
    },
    {
      id: "k8s-production",
      title: "Kubernetes for Production Teams",
      instructor: "James Whitaker",
      category: "cloud",
      level: "Expert",
      rating: 4.6,
      reviews: 2900,
      hours: 20,
      lectures: 80,
      students: 21000,
      price: "Included",
      badge: "",
      desc: "Deployments, services, probes, and rollouts. The cluster after the hello-world YAML.",
      outcomes: ["Workloads that stay up", "Health probes", "Config and secrets", "A safe rollout plan"]
    },
    {
      id: "android-kotlin",
      title: "Android Apps with Kotlin",
      instructor: "Kenji Sato",
      category: "mobile",
      level: "Advanced",
      rating: 4.7,
      reviews: 4800,
      hours: 22,
      lectures: 90,
      students: 34000,
      price: "Included",
      badge: "New",
      desc: "Screens, lists, and a small app you can install. Mobile after web — not a toy clicker.",
      outcomes: ["Kotlin basics for apps", "Layouts and navigation", "Lists from data", "An installable APK"]
    },
    {
      id: "figma-to-html",
      title: "Figma to HTML: Design Handoff",
      instructor: "Hana Kim",
      category: "design",
      level: "Intermediate",
      rating: 4.8,
      reviews: 3600,
      hours: 8,
      lectures: 38,
      students: 27000,
      price: "Free",
      badge: "",
      desc: "Read a file, measure spacing, and build the page. Designers and developers finally speaking the same layout.",
      outcomes: ["Read a Figma file", "Spacing and type scale", "Assets export", "A matching HTML page"]
    },
    {
      id: "mysql-queries",
      title: "MySQL: Tables, Joins & Reports",
      instructor: "Elena Petrova",
      category: "db",
      level: "Intermediate",
      rating: 4.7,
      reviews: 5100,
      hours: 11,
      lectures: 50,
      students: 43000,
      price: "Free",
      badge: "New",
      desc: "Create tables, join them, and answer a business question with a query — not a screenshot of Excel.",
      outcomes: ["Schema that makes sense", "SELECT with joins", "Group and filter", "A short data report"]
    },
    {
      id: "rust-systems",
      title: "Rust for Systems Thinking",
      instructor: "Rahul Mehta",
      category: "cs",
      level: "Expert",
      rating: 4.6,
      reviews: 1800,
      hours: 24,
      lectures: 96,
      students: 12000,
      price: "Included",
      badge: "",
      desc: "Ownership, memory, and a CLI tool that does not crash on bad input. Expert CS with a language that bites back.",
      outcomes: ["Ownership and borrowing", "Error handling", "A CLI project", "Tests you trust"]
    },
    {
      id: "staff-eng-path",
      title: "Staff Engineer: Design, Review & Mentorship",
      instructor: "Prof. Martin Cole",
      category: "career",
      level: "Expert",
      rating: 4.8,
      reviews: 1400,
      hours: 12,
      lectures: 42,
      students: 9000,
      price: "Included",
      badge: "Career",
      desc: "Write a design doc, review a PR with care, and grow a junior without taking the keyboard.",
      outcomes: ["A clear design doc", "Review that teaches", "Scope a project", "Mentor habits"]
    },
    {
      id: "photo-edit-basics",
      title: "Photos, Screenshots & Simple Editing",
      instructor: "Hana Kim",
      category: "basics",
      level: "Beginner",
      rating: 4.5,
      reviews: 1600,
      hours: 5,
      lectures: 22,
      students: 14000,
      price: "Free",
      badge: "",
      desc: "Crop, resize, and annotate a screenshot for class, a ticket, or a slide. Visual basics before design courses.",
      outcomes: ["Crop and resize", "Annotate a screenshot", "Save the right format", "A clean image for slides"]
    },
    {
      id: "jwt-auth-apis",
      title: "Auth for APIs: Sessions, JWT & Roles",
      instructor: "Sofia Alvarez",
      category: "web",
      level: "Advanced",
      rating: 4.7,
      reviews: 3300,
      hours: 10,
      lectures: 46,
      students: 22000,
      price: "Included",
      badge: "",
      desc: "Login that is not a toy. Tokens, refresh, and who can hit which route.",
      outcomes: ["Session vs token", "JWT flow", "Role checks", "A locked-down API"]
    },
    {
      id: "network-plus-lab",
      title: "Networking Lab: IP, DNS & Packets",
      instructor: "Nadia Rahman",
      category: "security",
      level: "Beginner",
      rating: 4.6,
      reviews: 2700,
      hours: 9,
      lectures: 40,
      students: 18000,
      price: "Free",
      badge: "New",
      desc: "How a request finds a server. IP, DNS, ports, and a lab you can repeat — the missing beginner layer before cloud.",
      outcomes: ["IP and subnets in plain talk", "DNS lookup practice", "Ports and protocols", "A small packet lab"]
    }
  ],

  studySubjects: [
    {
      id: "intro-cs",
      name: "Intro to Computer Science",
      level: "Beginner",
      units: 8,
      hours: 22,
      mastery: 12,
      color: "#1A9B8E",
      blurb: "How computers think, store, and run programs — the Khan-style foundation under every IT course."
    },
    {
      id: "python-lab",
      name: "Programming with Python",
      level: "Beginner",
      units: 10,
      hours: 28,
      mastery: 34,
      color: "#0E2340",
      blurb: "Interactive lessons, practice, and unit tests. Write, run, and master Python one skill at a time."
    },
    {
      id: "js-web",
      name: "JavaScript & the Web",
      level: "Beginner",
      units: 9,
      hours: 26,
      mastery: 8,
      color: "#E85D4C",
      blurb: "From values to the browser. Practice exercises after every concept, not just videos."
    },
    {
      id: "algebra-coders",
      name: "Algebra for Coders",
      level: "Beginner",
      units: 12,
      hours: 30,
      mastery: 55,
      color: "#D4A017",
      blurb: "The algebra you actually need for algorithms, graphics, and data — with mastery levels."
    },
    {
      id: "stats-lab",
      name: "Statistics & Probability",
      level: "Intermediate",
      units: 11,
      hours: 32,
      mastery: 20,
      color: "#3D6B9A",
      blurb: "Distributions, sampling, and intuition. Built like a study hall, not a lecture dump."
    },
    {
      id: "ds-units",
      name: "Data Structures",
      level: "Intermediate",
      units: 9,
      hours: 24,
      mastery: 5,
      color: "#1A9B8E",
      blurb: "Arrays to trees with visual tracing and practice sets. Master a structure before the next."
    },
    {
      id: "algo-units",
      name: "Algorithms",
      level: "Advanced",
      units: 10,
      hours: 28,
      mastery: 0,
      color: "#E85D4C",
      blurb: "Searching, sorting, graphs, and DP with step-by-step walkthroughs and unit challenges."
    },
    {
      id: "sql-lab",
      name: "SQL Practice Lab",
      level: "Beginner",
      units: 7,
      hours: 16,
      mastery: 41,
      color: "#0E2340",
      blurb: "Query drills on real-ish tables. Instant feedback, like a patient tutor sitting next to you."
    },
    {
      id: "networks",
      name: "Computer Networks",
      level: "Intermediate",
      units: 8,
      hours: 20,
      mastery: 0,
      color: "#3D6B9A",
      blurb: "Packets, HTTP, DNS, and the path of a request — CS that makes cloud and security click."
    },
    {
      id: "how-computers",
      name: "How Computers Work",
      level: "Beginner",
      units: 6,
      hours: 14,
      mastery: 70,
      color: "#D4A017",
      blurb: "Bits, memory, CPU, and OS ideas in plain language. Perfect before systems or cybersecurity.",
      image: "how-computers"
    },
    {
      id: "office-lab",
      name: "Office Skills Practice",
      level: "Beginner",
      units: 6,
      hours: 12,
      mastery: 15,
      color: "#1A9B8E",
      blurb: "Word, Excel, and slides in short drills. Original practice sets — not copied worksheets."
    }
  ],

  studyUnits: {
    "intro-cs": [
      { title: "What is a computer?", lessons: 4, type: "lesson", body: "A computer follows instructions, very fast, without guessing. Hardware is the body; software is the list of steps. If you can name input, process, and output for a task, you already understand the machine." },
      { title: "Binary & data", lessons: 5, type: "lesson" },
      { title: "Algorithms in plain English", lessons: 4, type: "lesson" },
      { title: "Programming vs. hardware", lessons: 3, type: "lesson" },
      { title: "Unit quiz: foundations", lessons: 1, type: "quiz" },
      { title: "Memory & storage", lessons: 4, type: "lesson" },
      { title: "Operating systems snapshot", lessons: 3, type: "lesson" },
      { title: "Mastery challenge", lessons: 1, type: "mastery" }
    ],
    "python-lab": [
      { title: "Values, types, variables", lessons: 6, type: "lesson" },
      { title: "Control flow", lessons: 5, type: "lesson" },
      { title: "Practice: loops & branches", lessons: 1, type: "practice" },
      { title: "Functions", lessons: 5, type: "lesson" },
      { title: "Lists & dictionaries", lessons: 6, type: "lesson" },
      { title: "Unit test: data & functions", lessons: 1, type: "quiz" },
      { title: "Files & errors", lessons: 4, type: "lesson" },
      { title: "Small programs", lessons: 4, type: "project" },
      { title: "Problem-solving patterns", lessons: 4, type: "lesson" },
      { title: "Mastery challenge", lessons: 1, type: "mastery" }
    ]
  },

  paths: [
    {
      id: "frontend",
      name: "Front-End Developer",
      role: "Build the interfaces people use",
      months: "4–6",
      level: "Beginner → Advanced",
      courses: ["html-css-foundations", "javascript-zero", "responsive-design", "react-complete", "uiux-devs"],
      skills: ["HTML/CSS", "JavaScript", "React", "Accessibility"]
    },
    {
      id: "backend",
      name: "Back-End Developer",
      role: "APIs, data, and server logic",
      months: "5–7",
      level: "Beginner → Advanced",
      courses: ["python-beginners", "sql-fundamentals", "git-github", "node-express", "linux-cli"],
      skills: ["Python or Node", "SQL", "APIs", "Linux"]
    },
    {
      id: "fullstack",
      name: "Full-Stack Engineer",
      role: "Ship features across the stack",
      months: "8–12",
      level: "Beginner → Expert",
      courses: ["html-css-foundations", "javascript-zero", "react-complete", "node-express", "nextjs-fullstack", "system-design"],
      skills: ["React", "Node", "Next.js", "System design"]
    },
    {
      id: "analyst",
      name: "Data Analyst",
      role: "Turn data into decisions",
      months: "4–6",
      level: "Beginner → Intermediate",
      courses: ["python-beginners", "sql-fundamentals", "stats-it", "data-python", "career-tech"],
      skills: ["SQL", "Python", "Stats", "Visualization"]
    },
    {
      id: "mleng",
      name: "AI / ML Engineer",
      role: "Models that ship, not just notebooks",
      months: "10–14",
      level: "Intermediate → Expert",
      courses: ["python-beginners", "lin-alg-ml", "data-python", "ml-az", "pytorch-dl"],
      skills: ["Python", "ML", "PyTorch", "Math"]
    },
    {
      id: "cloud",
      name: "Cloud Engineer",
      role: "Infrastructure that scales",
      months: "6–9",
      level: "Intermediate → Advanced",
      courses: ["linux-cli", "git-github", "aws-architect", "docker-k8s"],
      skills: ["Linux", "AWS", "Docker", "Kubernetes"]
    },
    {
      id: "sec",
      name: "Cybersecurity Analyst",
      role: "Protect systems and people",
      months: "6–10",
      level: "Beginner → Advanced",
      courses: ["intro-networks-proxy", "linux-cli", "cyber-plus", "ethical-hacking"],
      skills: ["Networks", "Linux", "Defense", "Labs"]
    },
    {
      id: "mobile",
      name: "Mobile App Developer",
      role: "Apps on phones people carry",
      months: "5–8",
      level: "Beginner → Advanced",
      courses: ["programming", "flutter-apps", "uiux-devs", "git-github"],
      skills: ["Dart/Flutter", "UI", "APIs", "Stores"]
    }
  ],

  certs: [
    { id: "rwd", name: "Responsive Web Design", projects: 5, hours: 300, level: "Beginner", track: "Web" },
    { id: "jsalgo", name: "JavaScript Algorithms & Data Structures", projects: 5, hours: 300, level: "Intermediate", track: "Programming" },
    { id: "frontend", name: "Front-End Libraries", projects: 5, hours: 300, level: "Intermediate", track: "Web" },
    { id: "dataviz", name: "Data Visualization", projects: 5, hours: 250, level: "Intermediate", track: "Data" },
    { id: "backend", name: "Back End & APIs", projects: 5, hours: 300, level: "Intermediate", track: "Web" },
    { id: "python", name: "Python Programming", projects: 5, hours: 280, level: "Beginner", track: "Programming" },
    { id: "ds", name: "Data Science", projects: 5, hours: 350, level: "Advanced", track: "Data" },
    { id: "ml", name: "Machine Learning", projects: 5, hours: 400, level: "Advanced", track: "AI" },
    { id: "cloud", name: "Cloud Foundations", projects: 4, hours: 220, level: "Intermediate", track: "Cloud" },
    { id: "sec", name: "Cybersecurity Basics", projects: 4, hours: 240, level: "Intermediate", track: "Security" }
  ],

  programs: [
    {
      name: "PG Program in Full-Stack Development",
      partner: "Industry mentors",
      weeks: 24,
      outcome: "Job-ready full-stack portfolio"
    },
    {
      name: "Professional Certificate in Data Science",
      partner: "Analytics track",
      weeks: 20,
      outcome: "Capstone + interview prep"
    },
    {
      name: "Cloud & DevOps Bootcamp",
      partner: "Platform labs",
      weeks: 16,
      outcome: "Deployed pipeline project"
    }
  ],

  instructors: [
    {
      id: "farah-siddiqui",
      name: "Farah Siddiqui",
      role: "Computer basics & MS Office",
      location: "Karachi, Pakistan",
      years: 9,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Farah spent nine years teaching office software in Karachi colleges before joining LMS Academy. She starts people on a real PC — power on, files, Word, Excel, email — not a coding bootcamp on day one.",
        "Her classrooms are slow on purpose: every shortcut is shown twice, then practiced on a messy desktop students actually own. Thousands of first-job learners came through her MS Office and Excel dashboard courses.",
        "She still runs weekend labs for people who have never attached a file to email. That patience is why beginners stay, then move to Omar’s Git and Ayesha’s first web page."
      ]
    },
    {
      id: "omar-farooq",
      name: "Omar Farooq",
      role: "Linux, Git & computer basics",
      location: "Lahore, Pakistan",
      years: 11,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Omar was a sysadmin who taught night classes after on-call. He now teaches Windows habits, the terminal, and Git the way shipping teams actually use them — not a museum of commands.",
        "Learners meet him after Farah’s office track: Chrome, files, then Linux permissions and a first real commit. His labs break on purpose so students learn to read an error instead of restarting the machine.",
        "He still keeps a small server at home for demos. If a lesson cannot be rebuilt from notes, it does not ship on this campus."
      ]
    },
    {
      id: "hana-kim",
      name: "Hana Kim",
      role: "UI/UX, Figma & visual basics",
      location: "Seoul, South Korea",
      years: 8,
      rating: 4.7,
      photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Hana is a product designer who still writes HTML. She coaches screenshots, Figma handoff, and the spacing hiring managers notice in a portfolio — not a slide deck of design jargon.",
        "Her courses sit between beginner computer skills and Ayesha’s web layouts: crop a photo, annotate a ticket, then match a Figma file in the browser.",
        "She reviews student work like a studio lead: one clear note, one next step. Designers and developers in her rooms finally share a layout language."
      ]
    },
    {
      id: "ayesha-malik",
      name: "Ayesha Malik",
      role: "HTML, CSS & responsive web",
      location: "Islamabad, Pakistan",
      years: 7,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Ayesha built marketing sites for local businesses, then taught the same layouts in class. Her pages are accessible, responsive, and meant to ship — not a CodePen that dies on a phone.",
        "HTML, CSS, Flexbox, Grid, and Bootstrap: three courses, one story. Students leave with a personal site they can defend in an interview.",
        "She pairs with Hana on design handoff and with Daniel when JavaScript has to land on a real DOM. The campus web path starts at her desk."
      ]
    },
    {
      id: "daniel-okonkwo",
      name: "Daniel Okonkwo",
      role: "JavaScript, VS Code & DSA",
      location: "Lagos, Nigeria",
      years: 10,
      rating: 4.9,
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Daniel started as a self-taught front-end engineer in Lagos. He is known for slow, project-based JavaScript — from first script in VS Code to interview DSA you can talk through out loud.",
        "His three courses form a ladder: editor setup, interactive pages, then algorithms. He will not skip the boring loop that makes the clever trick possible.",
        "Alumni send him offer letters. He asks for the GitHub instead. If the repo is messy, the next cohort hears why — kindly, and in public notes."
      ]
    },
    {
      id: "priya-raman",
      name: "Priya Raman",
      role: "Python & data analysis",
      location: "Bengaluru, India",
      years: 12,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1607746882042-311afd84d9ab?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Priya was an analyst who got tired of notebooks that never left the laptop. She teaches Python, Pandas, and the one-page finding a manager will actually read.",
        "Four courses, one habit: clean the CSV, chart what matters, write the sentence. No kaggle tourism. No mystery libraries on day one.",
        "She still consults one afternoon a week so the datasets in class match the mess of a real quarter close."
      ]
    },
    {
      id: "elena-petrova",
      name: "Elena Petrova",
      role: "SQL, MySQL & statistics",
      location: "Sofia, Bulgaria",
      years: 14,
      rating: 4.7,
      photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Elena is a database engineer who teaches joins with tables you can draw on paper. Statistics stay honest: sampling, inference, and a query you can explain to a non-engineer.",
        "SQL fundamentals, MySQL reports, and stats for IT — three courses that stop people from screenshotting Excel into a slide and calling it analysis.",
        "She trained analysts in Sofia before LMS Academy. Her rule: if you cannot name the grain of the table, you do not JOIN yet."
      ]
    },
    {
      id: "noah-berg",
      name: "Noah Berg",
      role: "React, Next.js & TypeScript",
      location: "Austin, USA",
      years: 9,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Noah is a full-stack contractor who still ships client dashboards. He teaches React, Next.js, and TypeScript the way production teams write them — hooks, routing, types, then deploy.",
        "Students come from Daniel’s JavaScript. They leave with an app that survives a refresh and a type error that means something.",
        "He records lessons after real standups, so the bugs in class are the bugs from Tuesday, not a tutorial from 2018."
      ]
    },
    {
      id: "sofia-alvarez",
      name: "Sofia Alvarez",
      role: "Node, APIs & MongoDB",
      location: "Mexico City, Mexico",
      years: 11,
      rating: 4.7,
      photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Sofia ran on-call for a payments API. Her Node, Express, Mongo, Docker, and auth courses come from nights spent keeping routes up — not a hello-world server that never sees traffic.",
        "Four courses: APIs, Mongo, Docker pipelines, and JWT that is not a toy. She pairs with James when the work moves to Kubernetes on AWS.",
        "She will fail a lab that has no health check. Students remember that more than any slide."
      ]
    },
    {
      id: "rahul-mehta",
      name: "Rahul Mehta",
      role: "Java, DSA, Rust & system design",
      location: "Pune, India",
      years: 13,
      rating: 4.6,
      photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Rahul interviewed engineers at a large product company and got tired of clever answers with no diagram. He drills Java, complexity, Rust, and system design until a whiteboard has a real box-and-arrow story.",
        "Three expert-leaning courses. He will stop a student who jumps to microservices before they can explain a lock.",
        "Office hours are a queue. Bring a failed test, not a motivational question."
      ]
    },
    {
      id: "dr-leila-hassan",
      name: "Dr. Leila Hassan",
      role: "Machine learning & LLM apps",
      location: "Amman, Jordan",
      years: 15,
      rating: 4.7,
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Leila holds a PhD in applied machine learning. She teaches models and LLM apps with guardrails — notebooks that become demos, not slide decks of accuracy numbers nobody can reproduce.",
        "Theory to practice, PyTorch, then a small RAG app that answers from your own notes. Hype is a failing grade.",
        "She publishes lab errata the same week a library breaks. That is the job, she says, not a trailer for a course."
      ]
    },
    {
      id: "james-whitaker",
      name: "James Whitaker",
      role: "AWS, Terraform & Kubernetes",
      location: "Manchester, UK",
      years: 16,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "James is a cloud architect. Every lab is rebuildable: VPC, IAM, Terraform state, then a Kubernetes rollout — no mystery clicks in a console you cannot screenshot twice.",
        "Three courses from practitioner to production cluster. He learned this the expensive way, on teams that could not recreate last Friday’s outage.",
        "Bring a diagram to class. If you cannot draw the packet path, you do not get the YAML yet."
      ]
    },
    {
      id: "nadia-rahman",
      name: "Nadia Rahman",
      role: "Cybersecurity & networking",
      location: "Dhaka, Bangladesh",
      years: 10,
      rating: 4.7,
      photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Nadia was a blue-team analyst. She teaches packets, DNS, and defensive labs before anyone talks about “hacking a site.” Curiosity without a lab is just a blog post.",
        "Networking for beginners, cybersecurity foundations, and ethical hacking with a written scope. Three courses, one ethic: you break only what you own.",
        "She still reads incident reports on Sunday. Monday’s lesson changes if the industry did."
      ]
    },
    {
      id: "kenji-sato",
      name: "Kenji Sato",
      role: "Flutter, Android & Kotlin",
      location: "Osaka, Japan",
      years: 8,
      rating: 4.7,
      photo: "https://images.unsplash.com/photo-1527980965255-ce40b3c2e65e?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Kenji shipped store apps for small Osaka businesses. His mobile courses end with something you can install — not a screenshot of a simulator.",
        "Flutter and Kotlin: two courses, same standard. Lists from data, navigation that does not trap the back button, a build you can hand to a tester.",
        "He keeps a cheap Android phone on the desk. If it janks there, the lesson is not done."
      ]
    },
    {
      id: "prof-martin-cole",
      name: "Prof. Martin Cole",
      role: "Math, CS foundations & career craft",
      location: "Toronto, Canada",
      years: 22,
      rating: 4.8,
      photo: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&crop=faces&w=800&h=800&q=80",
      bio: [
        "Martin taught discrete math and linear algebra in university, then coached senior engineers. His classes stay precise and human — proofs that earn a program, interviews that earn an offer.",
        "Four courses: discrete math, linear algebra for ML, the staff-engineer path, and the career studio for portfolios. He will not let a slogan replace a worked example.",
        "Office hours feel like a seminar. Bring a question you already tried to answer on paper."
      ]
    }
  ],

  reviews: [
    {
      name: "Sara K.",
      role: "Career switcher",
      photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
      text: "Study Hub felt like a patient classroom, but every path ended in a real IT project."
    },
    {
      name: "Bilal A.",
      role: "CS student",
      photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      text: "Beginner to expert filters saved me. I stopped jumping into advanced ML before finishing Python."
    },
    {
      name: "Mei L.",
      role: "Junior developer",
      photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80",
      text: "Certificates here mean projects. That is what I needed."
    }
  ],

  courseImages: {
    "computer-basics": "https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?auto=format&fit=crop&w=900&q=80",
    "ms-office": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80",
    "internet-google": "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=900&q=80",
    "typing-safety": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
    "html-css-foundations": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80",
    "javascript-zero": "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?auto=format&fit=crop&w=900&q=80",
    "python-beginners": "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=900&q=80",
    "git-github": "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=900&q=80",
    "sql-fundamentals": "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=900&q=80",
    "responsive-design": "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=900&q=80",
    "react-complete": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=900&q=80",
    "node-express": "https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=900&q=80",
    "data-python": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80",
    "java-dsa": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
    "linux-cli": "https://images.unsplash.com/photo-1629654291663-b91ad427698f?auto=format&fit=crop&w=900&q=80",
    "uiux-devs": "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=900&q=80",
    "ml-az": "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",
    "aws-architect": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80",
    "cyber-plus": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=900&q=80",
    "docker-k8s": "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=900&q=80",
    "flutter-apps": "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=900&q=80",
    "nextjs-fullstack": "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=900&q=80",
    "pytorch-dl": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=900&q=80",
    "system-design": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80",
    "ethical-hacking": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80",
    "discrete-math": "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=900&q=80",
    "lin-alg-ml": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=900&q=80",
    "dsa-mastery": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=900&q=80",
    "stats-it": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80",
    "career-tech": "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=900&q=80",
    "excel-dashboards": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80",
    "chrome-pc-habits": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=900&q=80",
    "meetings-zoom": "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=900&q=80",
    "vscode-first": "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=900&q=80",
    "bootstrap-layouts": "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=900&q=80",
    "python-scripts": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80",
    "typescript-js": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    "mongodb-node": "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?auto=format&fit=crop&w=900&q=80",
    "pandas-stories": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80",
    "llm-apps": "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",
    "terraform-aws": "https://images.unsplash.com/photo-1544197150-b99a5804f8b7?auto=format&fit=crop&w=900&q=80",
    "k8s-production": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    "android-kotlin": "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=900&q=80",
    "figma-to-html": "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=900&q=80",
    "mysql-queries": "https://images.unsplash.com/photo-1489875347897-49fbc7462794?auto=format&fit=crop&w=900&q=80",
    "rust-systems": "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=900&q=80",
    "staff-eng-path": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=900&q=80",
    "photo-edit-basics": "https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=900&q=80",
    "jwt-auth-apis": "https://images.unsplash.com/photo-1510511459019-5dda7724ec03?auto=format&fit=crop&w=900&q=80",
    "network-plus-lab": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80"
  },

  studyImages: {
    "intro-cs": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=80",
    "python-lab": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=700&q=80",
    "js-web": "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?auto=format&fit=crop&w=700&q=80",
    "algebra-coders": "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?auto=format&fit=crop&w=700&q=80",
    "stats-lab": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=700&q=80",
    "ds-units": "https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=700&q=80",
    "algo-units": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=700&q=80",
    "sql-lab": "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=700&q=80",
    "networks": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=700&q=80",
    "how-computers": "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=700&q=80",
    "office-lab": "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=700&q=80"
  }
};
